### ISSUE TITLE
storage service

### ISSUE THREAD

**Issue by reza250prog** [jamal-rahimzadegan/JS-Helpers#1]
hi . tnx for your efforts . I couldn't find storageService in your repository . I wanted to know if it exists or not

**Comment by jamal-rahimzadegan** [comment]
Hi. Thank you for your email. Here is the link, I will fix it.

https://github.com/jamal-rahimzadegan/tools/tree/master/src/modules/storage

**Comment by reza250prog** [comment]
Thank you
